package com.epam.pharmacy.command;

public enum CommandType {
    NOCOMMAND,
    LOGIN,
    LOGOUT,
    REGISTER,
    VIEWREGISTER,
    VIEWPROFILE,
    EDITPROFILE,
    VIEWCATALOG,
    VIEWHOMEPAGE,
    ADDTOORDER,
    CHECKPRESCRIPTION,
    RECHARGEBALANCE,
    USERORDERS,
    RENEWREQUEST,
    CREATEPRESCRIPTION,
    PROCESSREQUEST
}
